### ISSUE TITLE
Version 7.21.1 breaks on WASM

### ISSUE THREAD

**Issue by Mats-Hjalmar** [kosi-libs/Kodein#448]
I upgraded kodein to 7.21.1 from 7.20.1 and this happens in my project

1. Running the website is completely blank.
2. When refreshing the blank webpage i get this error.
3. After reverting to 7.20.1 it works as expected.

Uncaught runtime errors:
×
ERROR
Function 'withDI$composable' can not be called: No function found for symbol 'org.kodein.di.compose/withDI$composable|withDI$composable(org.kodein.di.DI;kotlin.Function2<androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>;androidx.compose.runtime.Composer?;kotlin.Int){}[0]'
IrLinkageError: Function 'withDI$composable' can not be called: No function found for symbol 'org.kodein.di.compose/withDI$composable|withDI$composable(org.kodein.di.DI;kotlin.Function2<androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>;androidx.compose.runtime.Composer?;kotlin.Int){}[0]'
    at throwLinkageError (webpack-internal:///./kotlin/kotlin-kotlin-stdlib.js:6431:11)
    at ComposableSingletons$BackofficeAppKt$lambda_2$lambda_oqtfkd (webpack-internal:///./kotlin/KattvikApp-backoffice.js:230:7)
    at protoOf.invoke_z8di7s_k$ (webpack-internal:///./kotlin/compose-multiplatform-core-runtime.js:32473:92)
    at eval (webpack-internal:///./kotlin/KattvikApp-backoffice.js:219:25)
    at eval (webpack-internal:///./kotlin/compose-multiplatform-core-material3.js:6543:9)
    at protoOf.invoke_z8di7s_k$ (webpack-internal:///./kotlin/compose-multiplatform-core-runtime.js:32473:92)
    at eval (webpack-internal:///./kotlin/compose-multiplatform-core-material3.js:6565:25)
    at CompositionLocalProvider$composable (webpack-internal:///./kotlin/compose-multiplatform-core-runtime.js:7515:5)
    at Surface$composable (webpack-internal:///./kotlin/compose-multiplatform-core-material3.js:6339:5)
    at eval (webpack-internal:///./kotlin/KattvikApp-backoffice.js:5121:9)

**Comment by romainbsl** [comment]
[7.21.2](https://github.com/kosi-libs/Kodein/releases/tag/v7.21.2) coming right up (currently publishing) with Compose Multiplatform 1.6.0-alpha01 and Wasm support fixed.
Tested against https://github.com/romainbsl/compose-multiplatform-with-kodein
Thanks for the report.
