### ISSUE TITLE
How to provide disable Kodein shared preferences module

### ISSUE THREAD

**Issue by daniel-waiguru** [kosi-libs/Kodein#451]
I am working on a project with the android module enabled `import(androidXModule(this))` but I need to provide a new secure SharedPreferences implementation without removing `import(androidXModule(this))` how do I disable the sharedpreference only from the androidx module?

**Comment by romainbsl** [comment]
You cannot disable part of a module. However, you can override it.

**Comment by daniel-waiguru** [comment]
Overriding it throws an exception.
`Caused by: org.kodein.di.Kodein$OverridingException: Binding bind<SharedPreferences>() with ? { ? } must override an existing binding.
                                                                                                    	at org.kodein.di.internal.KodeinContainerBuilderImpl.checkOverrides(KodeinContainerBuilderImpl.kt:106)
                                                                                                    	at org.kodein.di.internal.KodeinContainerBuilderImpl.bind(KodeinContainerBuilderImpl.kt:115)
                                                                                                    	at org.kodein.di.internal.KodeinBuilderImpl$TypeBinder.with(KodeinBuilderImpl.kt:20)`

Or am I missing something?

**Comment by romainbsl** [comment]
Yeah, SharedPrefences is scoped on the Android Context, see the definition here:

https://github.com/kosi-libs/Kodein/blob/c9d169d73fe4e99c43febcdcead92e9d3ff8c7d3/framework/android/kodein-di-framework-android-core/src/main/java/org/kodein/di/android/module.kt#L104

You probably need to do something like:
```kotlin
val contextToken = generic<Context>()
bind(overrides = true) { Provider(contextToken, generic()) { /* Your implementation */ } }
```

Or:

```kotlin
bind(overrides = true) { contexted<Context>().provider { /* Your implementation */ } }
```
