### ISSUE TITLE
R8 fullmode Causes java.lang.RuntimeException: Invalid TypeToken; must specify type parameters

### ISSUE THREAD

**Issue by daniel-waiguru** [kosi-libs/Kodein#452]
Using Kodein 6.2.1 with r8 fullmode enabled causes this crash
`
java.lang.RuntimeException: Unable to instantiate application <packagename>.Application package <package_name: java.lang.RuntimeException: Invalid TypeToken; must specify type parameters
                                                                                                    	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1477)
                                                                                                    	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1399)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6830)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2145)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8010)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:566)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
                                                                                                    Caused by: java.lang.RuntimeException: Invalid TypeToken; must specify type parameters
                                                                                                    	at org.kodein.di.TypeReference.<init>(SourceFile:272)
                                                                                                    	at <pacckagname>.Application$special$$inlined$instance$default$1.<init>(SourceFile:282)
                                                                                                    	at <packagename>.Application.<init>(SourceFile:282)
                                                                                                    	at java.lang.Class.newInstance(Native Method)
                                                                                                    	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
                                                                                                    	at androidx.core.app.CoreComponentFactory.instantiateApplication(SourceFile:52)
                                                                                                    	at android.app.Instrumentation.newApplication(Instrumentation.java:1232)
`

**Comment by romainbsl** [comment]
You can add pro guard rules like 
https://kosi-libs.org/kodein/7.21/framework/android.html#_proguard_configuration.

Latest versions of Kodein embed them already.

**Comment by daniel-waiguru** [comment]
I have added these rules but still the error persists

**Comment by romainbsl** [comment]
I'll have a look. Trying to reproduce.

**Comment by daniel-waiguru** [comment]
Updating the Kodein version necessitates regression testing which is not in the pipeline, I have these rules https://kosi-libs.org/kodein/7.21/framework/android.html#_proguard_configuration in my proguard rules

**Comment by romainbsl** [comment]
Those rules only apply for 7.6+. Old Kodein versions have a different type system. So the rules should be different. You should add TypeReference to your rules.

**Comment by romainbsl** [comment]
I don't really know, looking at old code [here](https://github.com/kosi-libs/Kodein/blob/274847d103ade2c3531b6bce8fd9b17626674127/kodein-di-core/src/commonMain/kotlin/org/kodein/di/typeToken.kt), [here](https://github.com/kosi-libs/Kodein/blob/274847d103ade2c3531b6bce8fd9b17626674127/kodein-di-core/src/jvmMain/kotlin/org/kodein/di/types.kt) and [here](https://github.com/kosi-libs/Kodein/blob/274847d103ade2c3531b6bce8fd9b17626674127/kodein-di-core/src/commonMain/kotlin/org/kodein/di/Typed.kt), rules could be those:
```properties
-keep, allowobfuscation, allowoptimization class org.kodein.di.Typed
-keep, allowobfuscation, allowoptimization class org.kodein.di.TypeToken
-keep, allowobfuscation, allowoptimization class org.kodein.di.CompositeTypeToken
-keep, allowobfuscation, allowoptimization class org.kodein.di.JVMTypeToken
-keep, allowobfuscation, allowoptimization class org.kodein.di.WrappingTest

-keep, allowobfuscation, allowoptimization class * extends org.kodein.di.Typed
-keep, allowobfuscation, allowoptimization class * extends org.kodein.di.TypeToken
-keep, allowobfuscation, allowoptimization class * extends org.kodein.di.CompositeTypeToken
-keep, allowobfuscation, allowoptimization class * extends org.kodein.di.JVMTypeToken
-keep, allowobfuscation, allowoptimization class * extends class org.kodein.di.WrappingTest
```
